### ISSUE TITLE
minikube not able to pull images

### ISSUE THREAD

**Issue by ksanjeev9211** [ThomasVitale/cloud-native-spring-in-action#34]
I am going through your book and trying to follow all the lessons, howver, I am now stuck on chapter 07 because the minikube is not able to pull the postgres image. 
`kubectl apply -f services` I get the following when I try to execute `kubectl get pod`:

NAME                                                  READY   STATUS         RESTARTS   AGE
polar-postgres-5b5c6fd948-nm882   0/1     ErrImagePull      0                16s

I am behind a corporate proxy, and I have configured the required HTTPS_PROXY, HTTP_PROXY, and NO_PROXY.

Thanks

**Comment by ThomasVitale** [comment]
@ksanjeev9211 thanks for your question. Could you please share more info about your Minikube setup? Have you configured the three environment variables for both Minikube and Docker as explained [here](https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/)?

Also, could you share the result of `kubectl describe pod <pod-name>`?

Thank you

**Comment by ThomasVitale** [comment]
Since there hasn't been any news, I'm closing this issue for now, but feel free to open a new one should you still have some problems with the Minikube setup.

I have added a guide about using Minikube behind a proxy, with some useful links: https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/main/Guides/minikube-configuration-behind-a-proxy.md.
