### ISSUE TITLE
Chapter 06: Unable to Publish COntainer Image

### ISSUE THREAD

**Issue by nmuianga** [ThomasVitale/cloud-native-spring-in-action#54]
Dear @ThomasVitale,

On package job, the step to Publish Container Image is failing due to "**denied: permission_denied: The requested installation does not exist.**" My Personal Access Token has the following permissions: delete:packages, gist, read:user, repo, user:email, workflow, write:org, write:packages. Here is the snippet of the failing step:

`      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}`

What could be the reason to fail the publishing of the image?

Thanks in advance.

**Comment by ThomasVitale** [comment]
@nmuianga when using the `${{ secrets.GITHUB_TOKEN }}` placeholder, GitHub automatically injects a short-lived token configured with permissions that depend on what is configured in the workflow. The job in a workflow that is responsible for publishing images must declare the `packages: write` permission as follows.

```yaml
package:
    name: Package and Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
```

The examples in the book follow this setup for publishing images having the following format: `${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}`. In particular, `REGISTRY` must be equal to `ghcr.io` and `IMAGE_NAME` must be exactly the same as the repository name. The GitHub Actions workflows in the book don't need you to create custom Personal Access Tokens since the token automatically provided by GitHub is enough.

There might be reason for which you can't use the automatically provided token. For example, if you need `IMAGE_NAME` to be something else than the repository name, but you still want to publish to the GitHub Container Registry (ghcr.io), then you can create a Personal Access Token as described in the book. That token needs the `write:packages` scope. Is this your use case?

<img width="658" alt="Screenshot 2023-12-16 at 14 35 39" src="https://github.com/ThomasVitale/cloud-native-spring-in-action/assets/8523418/80c726f7-304d-4da7-a0cc-6449513aba6d">

You can then save the value of the newly generated token into a Secret in your GitHub repository. Since `GITHUB_TOKEN` is the name of the token automatically injected by GitHub, your custom token should have a different name to avoid conflicts. Could this be the reason for the error you experienced? In the snippet you shared, I can see that `${{ secrets.GITHUB_TOKEN }}` is used. If you want to use your Personal Access Token (let's say you saved it as a Secret with name `MY_CUSTOM_TOKEN`) , then the value passed to the Docker Login action should be `${{ secrets.MY_CUSTOM_TOKEN }}`.

**Comment by ThomasVitale** [comment]
Closing this for now. If you still have issues with publishing images, feel free to open a new issue. Thank you!
